# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ce9f6e50bc45070e5026dd91655fe2b7"
name = "demo-shop-front-only"
handle = "demo-shop-front-only-1"
application_url = "https://flag-pj-nascar-varying.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-38155377.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://flag-pj-nascar-varying.trycloudflare.com/auth/callback",
  "https://flag-pj-nascar-varying.trycloudflare.com/auth/shopify/callback",
  "https://flag-pj-nascar-varying.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
